version: '3'
services:
  swagger-editor:
    image: swaggerapi/swagger-editor
    ports:
      - "8095:8080"

  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8096:8080"
    volumes:
      - ./swagger.yaml:/openapi.json
    environment:
      SWAGGER_JSON: /openapi.json
