swagger: '2.0'
info:
    description: INAIA Trading API
    version: '1'
    title: Trading API
    contact:
        email: dev@inaia.de
    license:
        name: Apache 2.0
        url: http://www.apache.org/licenses/LICENSE-2.0.html
# tags are used for organizing operations
tags:
    - name: Trading
      description: API for Trading

# Added by API Auto Mocking Plugin
host: api-trading-staging.inaia.cloud
basePath: /api/v1
schemes:
    - https


paths:
  /instruments:
    get:
      summary: Get a list of trading instruments
      description: Retrieve a paginated list of trading instruments with various filter and sorting options.
      parameters:
        - name: order_by
          in: query
          description: Order by 'created_at' or 'updated_at'.
          required: false
          type: string
          enum: [created_at, updated_at]
        - name: per_page
          in: query
          description: Number of results to return per page.
          required: false
          type: integer
          minimum: 1
          maximum: 1000
        - name: order_direction
          in: query
          description: Direction of sorting, either ascending ('asc') or descending ('desc').
          required: false
          type: string
          enum: [asc, desc]
        - name: trading_status
          in: query
          description: Filter by trading status, either 'ACTIVE' or 'INACTIVE'.
          required: false
          type: string
          enum: [ACTIVE, INACTIVE]
      responses:
        200:
          description: A list of trading instruments with metadata
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  $ref: '#/definitions/Instrument'
              meta:
                $ref: '#/definitions/MetaData'
        400:
          description: Invalid input
        500:
          description: Internal server error


definitions:
  Instrument:
    type: object
    properties:
      id:
        type: string
      isin:
        type: string
      wkn:
        type: string
      name:
        type: string
      fractional_trading:
        type: boolean
      trading_status:
        type: string
        enum: [ACTIVE, INACTIVE]
      created_at:
        type: string
        format: date-time
      updated_at:
        type: string
        format: date-time
  MetaData:
    type: object
    properties:
      sort:
        type: string
      order:
        type: string
      offset:
        type: integer
      limit:
        type: integer
      count:
        type: integer
      total_count:
        type: integer
