<?php

namespace App\Repositories;

use App\Repositories\Contracts\TaxInterface;
use App\Repositories\Contracts\UserInterface;

class TaxRepository extends BaseRepository implements TaxInterface
{
//    public function save(array $data): \ArrayAccess
//    {
//        if (!isset($data['branch_id'])) {
//            $data['branch_id'] = 1;
//        }
//        return parent::save($data); // TODO: Change the autogenerated stub
//    }
}
